name: CI
on: [push]
jobs:
  rspec-tests:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      HOSTNAME: localhost
    services:
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rspec
  # rubocop:
  #   name: Linter
  #   needs: rspec-tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.0.0
  #         bundler-cache: true
  #     - name: Check code
  #       run: bundle exec rubocop
  deploy:
      needs: rspec-tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Deploy To Heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
            heroku_app_name: ${{secrets.HEROKU_APP}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
